const { createClient } = require('@supabase/supabase-js');
require('dotenv').config({ path: __dirname + '/../.env' });

const supabaseUrl = 'https://hubvhqfxlzwkrvpulkqs.supabase.co';
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1YnZocWZ4bHp3a3J2cHVsa3FzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2OTk1NzkxNCwiZXhwIjoyMDg1NTMzOTE0fQ.xDkBbV6dOmu0KGvNTIHxYRHD8IiYCq4brIJ5O4EHAzc';
const supabase = createClient(supabaseUrl, supabaseKey);

const t1Content = [
    { topic_id: 'c-p18-t1', content_type: 'explanation', content_text: '<h3 class="text-xl font-bold text-gray-900 dark:text-white mb-4">Introduction</h3><p class="text-gray-700 dark:text-gray-300">Writing a program that works is not enough. Professional programmers follow coding standards to make code readable, maintainable, and easy to understand by other developers.</p><p class="text-gray-700 dark:text-gray-300 mt-2">Imagine writing a book without spaces, punctuation, or paragraphs. The book may contain information, but it becomes difficult to read. The same applies to code.</p><p class="text-gray-700 dark:text-gray-300 mt-2">Coding standards are a set of guidelines that help developers write clean and organized programs.</p>', order_index: 1 },
    { topic_id: 'c-p18-t1', content_type: 'explanation', content_text: '<h3 class="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">Why Coding Standards Matter</h3><div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4"><div class="bg-gray-50 dark:bg-gray-800 p-4 rounded-xl border border-gray-200 dark:border-gray-700"><h4 class="font-bold text-blue-700 dark:text-blue-400 mb-2">Readability</h4><p class="text-sm text-gray-700 dark:text-gray-300">Clean code is easier to understand.</p></div><div class="bg-gray-50 dark:bg-gray-800 p-4 rounded-xl border border-gray-200 dark:border-gray-700"><h4 class="font-bold text-green-700 dark:text-green-400 mb-2">Maintainability</h4><p class="text-sm text-gray-700 dark:text-gray-300">Future changes become easier.</p></div><div class="bg-gray-50 dark:bg-gray-800 p-4 rounded-xl border border-gray-200 dark:border-gray-700"><h4 class="font-bold text-purple-700 dark:text-purple-400 mb-2">Team Collaboration</h4><p class="text-sm text-gray-700 dark:text-gray-300">Multiple developers can work on the same project efficiently.</p></div><div class="bg-gray-50 dark:bg-gray-800 p-4 rounded-xl border border-gray-200 dark:border-gray-700"><h4 class="font-bold text-red-700 dark:text-red-400 mb-2">Reduced Errors</h4><p class="text-sm text-gray-700 dark:text-gray-300">Well-structured code helps prevent mistakes.</p></div></div>', order_index: 2 },
    { topic_id: 'c-p18-t1', content_type: 'explanation', content_text: '<h3 class="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">Coding Standards in C</h3><h4 class="font-bold text-gray-900 dark:text-white mt-4 mb-2">1. Use Meaningful Variable Names</h4><div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-2"><div class="bg-red-50 dark:bg-red-900/20 p-4 rounded-xl border border-red-200 dark:border-red-800"><h5 class="font-bold text-red-700 dark:text-red-400 mb-2">Bad Example</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">int a;\nfloat x;</pre></div><div class="bg-green-50 dark:bg-green-900/20 p-4 rounded-xl border border-green-200 dark:border-green-800"><h5 class="font-bold text-green-700 dark:text-green-400 mb-2">Good Example</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">int studentAge;\nfloat accountBalance;</pre></div></div>', order_index: 3 },
    { topic_id: 'c-p18-t1', content_type: 'explanation', content_text: '<h4 class="font-bold text-gray-900 dark:text-white mt-6 mb-2">2. Proper Indentation</h4><div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-2"><div class="bg-red-50 dark:bg-red-900/20 p-4 rounded-xl border border-red-200 dark:border-red-800"><h5 class="font-bold text-red-700 dark:text-red-400 mb-2">Bad Example</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">if(age >= 18){\nprintf("Adult");\n}</pre></div><div class="bg-green-50 dark:bg-green-900/20 p-4 rounded-xl border border-green-200 dark:border-green-800"><h5 class="font-bold text-green-700 dark:text-green-400 mb-2">Good Example</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">if(age >= 18)\n{\n    printf("Adult");\n}</pre></div></div>', order_index: 4 },
    { topic_id: 'c-p18-t1', content_type: 'explanation', content_text: '<h4 class="font-bold text-gray-900 dark:text-white mt-6 mb-2">3. Write Comments</h4><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-gray-50 dark:bg-gray-800 p-3 rounded-xl border border-gray-200 dark:border-gray-700">// Calculate simple interest\ninterest = (principal * rate * time) / 100;</pre><p class="text-sm text-gray-700 dark:text-gray-300 mt-2">Comments explain the purpose of code.</p>', order_index: 5 },
    { topic_id: 'c-p18-t1', content_type: 'explanation', content_text: '<h4 class="font-bold text-gray-900 dark:text-white mt-6 mb-2">4. Use Consistent Naming</h4><div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-2"><div class="bg-red-50 dark:bg-red-900/20 p-4 rounded-xl border border-red-200 dark:border-red-800"><h5 class="font-bold text-red-700 dark:text-red-400 mb-2">Avoid</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">studentName\nAge\nm</pre></div><div class="bg-green-50 dark:bg-green-900/20 p-4 rounded-xl border border-green-200 dark:border-green-800"><h5 class="font-bold text-green-700 dark:text-green-400 mb-2">Consistent</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">studentName\nstudentAge\nstudentMarks</pre></div></div>', order_index: 6 },
    { topic_id: 'c-p18-t1', content_type: 'explanation', content_text: '<h4 class="font-bold text-gray-900 dark:text-white mt-6 mb-2">5. Keep Functions Small</h4><div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-2"><div class="bg-red-50 dark:bg-red-900/20 p-4 rounded-xl border border-red-200 dark:border-red-800"><h5 class="font-bold text-red-700 dark:text-red-400 mb-2">Bad</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">main()\n{\n    // 300 lines of code\n}</pre></div><div class="bg-green-50 dark:bg-green-900/20 p-4 rounded-xl border border-green-200 dark:border-green-800"><h5 class="font-bold text-green-700 dark:text-green-400 mb-2">Good</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">calculateMarks();\ndisplayResult();\nsaveData();</pre></div></div>', order_index: 7 },
    { topic_id: 'c-p18-t1', content_type: 'explanation', content_text: '<h3 class="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">Industry Best Practices</h3><ul class="list-disc pl-6 space-y-2 text-sm text-gray-700 dark:text-gray-300"><li>✔ Use meaningful names</li><li>✔ Follow indentation</li><li>✔ Write reusable functions</li><li>✔ Remove unused code</li><li>✔ Use comments wisely</li><li>✔ Avoid hardcoded values</li></ul><h4 class="font-bold text-gray-900 dark:text-white mt-6 mb-2">Real-World Example</h4><div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-2"><div class="bg-red-50 dark:bg-red-900/20 p-4 rounded-xl border border-red-200 dark:border-red-800"><h5 class="font-bold text-red-700 dark:text-red-400 mb-2">Bad</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">int x=5000;</pre></div><div class="bg-green-50 dark:bg-green-900/20 p-4 rounded-xl border border-green-200 dark:border-green-800"><h5 class="font-bold text-green-700 dark:text-green-400 mb-2">Good</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">#define MAX_USERS 5000</pre></div></div>', order_index: 8 },
];

const t2Content = [
    { topic_id: 'c-p18-t2', content_type: 'explanation', content_text: '<h3 class="text-xl font-bold text-gray-900 dark:text-white mb-4">Introduction</h3><p class="text-gray-700 dark:text-gray-300">No programmer writes perfect code on the first attempt.</p><p class="text-gray-700 dark:text-gray-300 mt-2">The process of finding and fixing errors in a program is called <strong>debugging</strong>.</p><p class="text-gray-700 dark:text-gray-300 mt-2">Debugging is one of the most important skills in software development.</p><h3 class="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">What is a Bug?</h3><p class="text-gray-700 dark:text-gray-300">A bug is an error that causes unexpected behavior.</p><div class="bg-gray-50 dark:bg-gray-800 p-4 rounded-xl border border-gray-200 dark:border-gray-700 mt-4"><h4 class="font-bold text-blue-700 dark:text-blue-400 mb-2">Example:</h4><p class="text-sm text-gray-700 dark:text-gray-300"><strong>Expected:</strong> 5 + 5 = 10</p><p class="text-sm text-red-600 dark:text-red-400 mt-1"><strong>Actual:</strong> 5 + 5 = 55</p></div>', order_index: 1 },
    { topic_id: 'c-p18-t2', content_type: 'explanation', content_text: '<h3 class="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">Types of Errors</h3><div class="space-y-4"><div class="bg-white dark:bg-gray-800 p-5 rounded-xl border border-gray-200 dark:border-gray-700 shadow-sm"><h4 class="font-bold text-gray-900 dark:text-white mb-2">1. Syntax Errors</h4><p class="text-sm text-gray-700 dark:text-gray-300 mb-2">Violations of language rules.</p><pre class="font-mono text-sm bg-gray-50 dark:bg-gray-900 p-2 rounded mb-2">printf("Hello")</pre><p class="text-xs text-red-500 italic">Missing semicolon.</p></div><div class="bg-white dark:bg-gray-800 p-5 rounded-xl border border-gray-200 dark:border-gray-700 shadow-sm"><h4 class="font-bold text-gray-900 dark:text-white mb-2">2. Runtime Errors</h4><p class="text-sm text-gray-700 dark:text-gray-300 mb-2">Occur while executing.</p><pre class="font-mono text-sm bg-gray-50 dark:bg-gray-900 p-2 rounded mb-2">int x = 10;\nint y = 0;\n\nprintf("%d", x/y);</pre><p class="text-xs text-red-500 italic">Division by zero.</p></div><div class="bg-white dark:bg-gray-800 p-5 rounded-xl border border-gray-200 dark:border-gray-700 shadow-sm"><h4 class="font-bold text-gray-900 dark:text-white mb-2">3. Logical Errors</h4><p class="text-sm text-gray-700 dark:text-gray-300 mb-2">Program runs but produces wrong output.</p><div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-2"><div class="bg-red-50 dark:bg-red-900/20 p-3 rounded border border-red-200 dark:border-red-800"><p class="text-xs font-bold text-red-700 dark:text-red-400 mb-1">Wrong Output:</p><code class="text-sm text-gray-800 dark:text-gray-200">area = length + width;</code></div><div class="bg-green-50 dark:bg-green-900/20 p-3 rounded border border-green-200 dark:border-green-800"><p class="text-xs font-bold text-green-700 dark:text-green-400 mb-1">Correct Output:</p><code class="text-sm text-gray-800 dark:text-gray-200">area = length * width;</code></div></div></div></div>', order_index: 2 },
    { topic_id: 'c-p18-t2', content_type: 'explanation', content_text: '<h3 class="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">Debugging Techniques</h3><ul class="space-y-4 text-gray-700 dark:text-gray-300"><li class="flex items-start"><span class="flex-shrink-0 w-6 h-6 flex items-center justify-center bg-blue-100 dark:bg-blue-900 text-blue-600 dark:text-blue-300 rounded-full font-bold text-sm mr-3">1</span><div><strong class="text-gray-900 dark:text-white block mb-1">Print Debugging</strong><code class="text-sm bg-gray-100 dark:bg-gray-800 px-1 py-0.5 rounded">printf("Value of total = %d", total);</code><p class="text-sm mt-1">Track variable values.</p></div></li><li class="flex items-start"><span class="flex-shrink-0 w-6 h-6 flex items-center justify-center bg-blue-100 dark:bg-blue-900 text-blue-600 dark:text-blue-300 rounded-full font-bold text-sm mr-3">2</span><div><strong class="text-gray-900 dark:text-white block mb-1">Break Large Problems</strong><p class="text-sm">Check: Input → Processing → Output.</p></div></li><li class="flex items-start"><span class="flex-shrink-0 w-6 h-6 flex items-center justify-center bg-blue-100 dark:bg-blue-900 text-blue-600 dark:text-blue-300 rounded-full font-bold text-sm mr-3">3</span><div><strong class="text-gray-900 dark:text-white block mb-1">Compiler Warnings</strong><p class="text-sm mb-1">Always read warnings.</p><code class="text-xs text-yellow-600 dark:text-yellow-400 bg-yellow-50 dark:bg-yellow-900/30 px-2 py-1 rounded block">warning: variable \'count\' is uninitialized</code></div></li><li class="flex items-start"><span class="flex-shrink-0 w-6 h-6 flex items-center justify-center bg-blue-100 dark:bg-blue-900 text-blue-600 dark:text-blue-300 rounded-full font-bold text-sm mr-3">4</span><div><strong class="text-gray-900 dark:text-white block mb-1">Test Edge Cases</strong><p class="text-sm">Check: 0, Negative numbers, Large values.</p></div></li></ul>', order_index: 3 },
    { topic_id: 'c-p18-t2', content_type: 'explanation', content_text: '<h3 class="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">Debugging Workflow</h3><div class="flex flex-col items-center max-w-sm mx-auto bg-gray-50 dark:bg-gray-800 p-6 rounded-xl border border-gray-200 dark:border-gray-700 shadow-sm"><div class="bg-blue-100 dark:bg-blue-900/50 text-blue-800 dark:text-blue-300 px-4 py-2 rounded-lg font-bold text-center w-full shadow-sm">Observe Error</div><div class="h-6 w-0.5 bg-gray-300 dark:bg-gray-600 my-1"></div><div class="bg-indigo-100 dark:bg-indigo-900/50 text-indigo-800 dark:text-indigo-300 px-4 py-2 rounded-lg font-bold text-center w-full shadow-sm">Identify Location</div><div class="h-6 w-0.5 bg-gray-300 dark:bg-gray-600 my-1"></div><div class="bg-purple-100 dark:bg-purple-900/50 text-purple-800 dark:text-purple-300 px-4 py-2 rounded-lg font-bold text-center w-full shadow-sm">Analyze Cause</div><div class="h-6 w-0.5 bg-gray-300 dark:bg-gray-600 my-1"></div><div class="bg-green-100 dark:bg-green-900/50 text-green-800 dark:text-green-300 px-4 py-2 rounded-lg font-bold text-center w-full shadow-sm">Fix Code</div><div class="h-6 w-0.5 bg-gray-300 dark:bg-gray-600 my-1"></div><div class="bg-yellow-100 dark:bg-yellow-900/50 text-yellow-800 dark:text-yellow-300 px-4 py-2 rounded-lg font-bold text-center w-full shadow-sm">Test Again</div></div>', order_index: 4 },
];

const t3Content = [
    { topic_id: 'c-p18-t3', content_type: 'explanation', content_text: '<h3 class="text-xl font-bold text-gray-900 dark:text-white mb-4">Introduction</h3><p class="text-gray-700 dark:text-gray-300">Every programmer makes mistakes. Understanding common errors helps you solve problems faster.</p><h3 class="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">1. Missing Semicolon</h3><div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-2"><div class="bg-red-50 dark:bg-red-900/20 p-4 rounded-xl border border-red-200 dark:border-red-800"><h5 class="font-bold text-red-700 dark:text-red-400 mb-2">Wrong</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">int marks = 100</pre></div><div class="bg-green-50 dark:bg-green-900/20 p-4 rounded-xl border border-green-200 dark:border-green-800"><h5 class="font-bold text-green-700 dark:text-green-400 mb-2">Correct</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">int marks = 100;</pre></div></div>', order_index: 1 },
    { topic_id: 'c-p18-t3', content_type: 'explanation', content_text: '<h3 class="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">2. Assignment Instead of Comparison</h3><div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-2"><div class="bg-red-50 dark:bg-red-900/20 p-4 rounded-xl border border-red-200 dark:border-red-800"><h5 class="font-bold text-red-700 dark:text-red-400 mb-2">Wrong</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">if(x = 10)</pre></div><div class="bg-green-50 dark:bg-green-900/20 p-4 rounded-xl border border-green-200 dark:border-green-800"><h5 class="font-bold text-green-700 dark:text-green-400 mb-2">Correct</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">if(x == 10)</pre></div></div><h3 class="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">3. Array Index Out of Bounds</h3><div class="bg-red-50 dark:bg-red-900/20 p-4 rounded-xl border border-red-200 dark:border-red-800 mt-2"><h5 class="font-bold text-red-700 dark:text-red-400 mb-2">Wrong</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">int arr[5];\n\narr[5] = 10;</pre><p class="text-sm text-red-800 dark:text-red-300 mt-2 font-medium">Valid indexes: 0 to 4.</p></div>', order_index: 2 },
    { topic_id: 'c-p18-t3', content_type: 'explanation', content_text: '<h3 class="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">4. Infinite Loops</h3><div class="bg-red-50 dark:bg-red-900/20 p-4 rounded-xl border border-red-200 dark:border-red-800 mt-2"><h5 class="font-bold text-red-700 dark:text-red-400 mb-2">Wrong</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">while(1)\n{\n}</pre><p class="text-sm text-red-800 dark:text-red-300 mt-2 font-medium">Without exit condition.</p></div><h3 class="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">5. Division By Zero</h3><div class="bg-red-50 dark:bg-red-900/20 p-4 rounded-xl border border-red-200 dark:border-red-800 mt-2"><h5 class="font-bold text-red-700 dark:text-red-400 mb-2">Wrong</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">int result = 100/0;</pre></div>', order_index: 3 },
    { topic_id: 'c-p18-t3', content_type: 'explanation', content_text: '<h3 class="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">6. Uninitialized Variables</h3><div class="bg-red-50 dark:bg-red-900/20 p-4 rounded-xl border border-red-200 dark:border-red-800 mt-2"><h5 class="font-bold text-red-700 dark:text-red-400 mb-2">Wrong</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">int age;\n\nprintf("%d", age);</pre></div><h3 class="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">7. Buffer Overflow</h3><div class="bg-red-50 dark:bg-red-900/20 p-4 rounded-xl border border-red-200 dark:border-red-800 mt-2"><h5 class="font-bold text-red-700 dark:text-red-400 mb-2">Wrong</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">char name[5];\n\nscanf("%s", name);</pre><p class="text-sm text-red-800 dark:text-red-300 mt-2 font-medium">Input larger than 5 characters causes issues.</p></div>', order_index: 4 },
    { topic_id: 'c-p18-t3', content_type: 'explanation', content_text: '<h3 class="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">Error Prevention Tips</h3><div class="bg-indigo-50 dark:bg-indigo-900/20 border-l-4 border-indigo-500 p-5 rounded-r-xl"><ul class="space-y-3 text-sm text-indigo-900 dark:text-indigo-200"><li class="flex items-center"><span class="text-indigo-500 mr-2">✔</span> Initialize variables</li><li class="flex items-center"><span class="text-indigo-500 mr-2">✔</span> Check array limits</li><li class="flex items-center"><span class="text-indigo-500 mr-2">✔</span> Validate user input</li><li class="flex items-center"><span class="text-indigo-500 mr-2">✔</span> Test edge cases</li><li class="flex items-center"><span class="text-indigo-500 mr-2">✔</span> Read compiler warnings</li></ul></div>', order_index: 5 },
];

const t4Content = [
    { topic_id: 'c-p18-t4', content_type: 'explanation', content_text: '<h3 class="text-xl font-bold text-gray-900 dark:text-white mb-4">Introduction</h3><p class="text-gray-700 dark:text-gray-300">Optimization is the process of improving code performance while maintaining correct output.</p><p class="text-gray-700 dark:text-gray-300 mt-2">Good optimization makes programs:</p><ul class="list-disc pl-6 mt-2 space-y-1 text-sm text-gray-700 dark:text-gray-300"><li>Faster</li><li>Smaller</li><li>More efficient</li></ul><h3 class="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">Why Optimization Matters</h3><div class="bg-gray-50 dark:bg-gray-800 p-5 rounded-xl border border-gray-200 dark:border-gray-700 mt-4"><p class="text-sm text-gray-800 dark:text-gray-200 mb-3">Imagine searching for a name:</p><ul class="space-y-2"><li class="text-sm text-gray-700 dark:text-gray-300"><strong class="text-gray-900 dark:text-white">Method 1:</strong> Search every record.</li><li class="text-sm text-gray-700 dark:text-gray-300"><strong class="text-gray-900 dark:text-white">Method 2:</strong> Use a sorted list.</li></ul><p class="text-sm font-bold text-green-600 dark:text-green-400 mt-3">Method 2 is much faster.</p></div>', order_index: 1 },
    { topic_id: 'c-p18-t4', content_type: 'explanation', content_text: '<h3 class="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">Types of Optimization</h3><div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-2"><div class="bg-blue-50 dark:bg-blue-900/20 p-4 rounded-xl border border-blue-200 dark:border-blue-800"><h4 class="font-bold text-blue-700 dark:text-blue-400 mb-2">Time Optimization</h4><p class="text-sm text-gray-700 dark:text-gray-300">Reduce execution time.</p></div><div class="bg-purple-50 dark:bg-purple-900/20 p-4 rounded-xl border border-purple-200 dark:border-purple-800"><h4 class="font-bold text-purple-700 dark:text-purple-400 mb-2">Memory Optimization</h4><p class="text-sm text-gray-700 dark:text-gray-300">Reduce memory usage.</p></div></div><h3 class="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">Example 1: Avoid Repeated Calculations</h3><div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-2"><div class="bg-red-50 dark:bg-red-900/20 p-4 rounded-xl border border-red-200 dark:border-red-800"><h5 class="font-bold text-red-700 dark:text-red-400 mb-2">Bad</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">for(int i=0;i<1000;i++)\n{\n    int area = 10 * 20;\n}</pre></div><div class="bg-green-50 dark:bg-green-900/20 p-4 rounded-xl border border-green-200 dark:border-green-800"><h5 class="font-bold text-green-700 dark:text-green-400 mb-2">Good</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">int area = 10 * 20;\n\nfor(int i=0;i<1000;i++)\n{\n}</pre></div></div>', order_index: 2 },
    { topic_id: 'c-p18-t4', content_type: 'explanation', content_text: '<h3 class="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">Example 2: Efficient Loops</h3><div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-2"><div class="bg-red-50 dark:bg-red-900/20 p-4 rounded-xl border border-red-200 dark:border-red-800"><h5 class="font-bold text-red-700 dark:text-red-400 mb-2">Bad</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">for(int i=0;i<=n-1;i++)</pre></div><div class="bg-green-50 dark:bg-green-900/20 p-4 rounded-xl border border-green-200 dark:border-green-800"><h5 class="font-bold text-green-700 dark:text-green-400 mb-2">Good</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">for(int i=0;i<n;i++)</pre></div></div><h3 class="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">Example 3: Use Appropriate Data Types</h3><div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-2"><div class="bg-red-50 dark:bg-red-900/20 p-4 rounded-xl border border-red-200 dark:border-red-800"><h5 class="font-bold text-red-700 dark:text-red-400 mb-2">Bad</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">long long age = 20;</pre></div><div class="bg-green-50 dark:bg-green-900/20 p-4 rounded-xl border border-green-200 dark:border-green-800"><h5 class="font-bold text-green-700 dark:text-green-400 mb-2">Good</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">int age = 20;</pre></div></div>', order_index: 3 },
    { topic_id: 'c-p18-t4', content_type: 'explanation', content_text: '<h3 class="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">Example 4: Remove Unused Variables</h3><div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-2"><div class="bg-red-50 dark:bg-red-900/20 p-4 rounded-xl border border-red-200 dark:border-red-800"><h5 class="font-bold text-red-700 dark:text-red-400 mb-2">Bad</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">int a,b,c,d,e,f,g;</pre></div><div class="bg-green-50 dark:bg-green-900/20 p-4 rounded-xl border border-green-200 dark:border-green-800"><h5 class="font-bold text-green-700 dark:text-green-400 mb-2">Good</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded">int totalMarks;</pre></div></div><h3 class="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">Example 5: Function Reuse</h3><div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-2"><div class="bg-red-50 dark:bg-red-900/20 p-4 rounded-xl border border-red-200 dark:border-red-800"><h5 class="font-bold text-red-700 dark:text-red-400 mb-2">Bad</h5><p class="text-sm text-gray-700 dark:text-gray-300">Same code repeated 10 times.</p></div><div class="bg-green-50 dark:bg-green-900/20 p-4 rounded-xl border border-green-200 dark:border-green-800"><h5 class="font-bold text-green-700 dark:text-green-400 mb-2">Good</h5><pre class="font-mono text-sm text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 p-2 rounded mb-1">calculateInterest();</pre><p class="text-xs text-gray-600 dark:text-gray-400">Call whenever needed.</p></div></div>', order_index: 4 },
    { topic_id: 'c-p18-t4', content_type: 'explanation', content_text: '<h3 class="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">Optimization Checklist</h3><div class="bg-indigo-50 dark:bg-indigo-900/20 border-l-4 border-indigo-500 p-5 rounded-r-xl"><ul class="grid grid-cols-1 md:grid-cols-2 gap-3 text-sm text-indigo-900 dark:text-indigo-200"><li class="flex items-center"><span class="text-indigo-500 mr-2">✔</span> Avoid duplicate code</li><li class="flex items-center"><span class="text-indigo-500 mr-2">✔</span> Reuse functions</li><li class="flex items-center"><span class="text-indigo-500 mr-2">✔</span> Reduce unnecessary loops</li><li class="flex items-center"><span class="text-indigo-500 mr-2">✔</span> Remove unused variables</li><li class="flex items-center"><span class="text-indigo-500 mr-2">✔</span> Choose proper data types</li><li class="flex items-center"><span class="text-indigo-500 mr-2">✔</span> Minimize memory usage</li></ul></div><h4 class="font-bold text-gray-900 dark:text-white mt-6 mb-2">Real Industry Example</h4><div class="bg-gray-50 dark:bg-gray-800 p-4 rounded-xl border border-gray-200 dark:border-gray-700"><p class="text-sm text-gray-700 dark:text-gray-300">A search engine processing millions of requests per second must use optimized algorithms. Even a 1% improvement can save huge computational resources.</p></div>', order_index: 5 },
];

async function updateTopics() {
    console.log('Updating Phase 18 topics 1-4 content...');

    const allContent = [...t1Content, ...t2Content, ...t3Content, ...t4Content];

    for (let i = 1; i <= 4; i++) {
        const topicId = `c-p18-t${i}`;
        console.log(`Clearing old content for ${topicId}...`);
        const { error: deleteError } = await supabase
            .from('topic_content')
            .delete()
            .eq('topic_id', topicId);

        if (deleteError) {
            console.error(`Error deleting ${topicId} content:`, deleteError);
        }
    }

    console.log('Inserting new content...');
    const { error: insertError } = await supabase
        .from('topic_content')
        .insert(allContent);

    if (insertError) {
        console.error('Error inserting content:', insertError);
    } else {
        console.log('Successfully updated content for Phase 18 Topics 1-4!');
    }
}

updateTopics();
